# Generated by Django 4.2.6 on 2023-10-31 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTC',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('bit_address', models.CharField(max_length=255)),
                ('status', models.CharField(db_comment='1=active 0=pending', max_length=255)),
                ('default', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bit_coins',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='BitCoins',
        ),
    ]
