# Generated by Django 4.2.6 on 2023-10-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_btc_delete_bitcoins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards1',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pv', models.CharField(max_length=255)),
                ('cash_equivalent', models.FloatField(blank=True, null=True)),
                ('rank', models.CharField(blank=True, max_length=191, null=True)),
                ('rank_image', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'awards',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Awards',
        ),
    ]
