# Generated by Django 4.2.6 on 2023-11-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_orderproduct_alter_orderitemmetas_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitemmetas',
            table=None,
        ),
    ]
